# Generated by Django 3.0.5 on 2020-05-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='map',
            field=models.TextField(default=''),
        ),
    ]
