# Generated by Django 3.0.5 on 2020-05-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200504_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='map',
            field=models.TextField(blank=True, default=''),
        ),
    ]
