# Generated by Django 3.0.5 on 2020-05-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200516_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pish',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
