# Generated by Django 3.0.5 on 2020-05-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_pish'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('frosh', 'frosh'), ('villa', 'villa'), ('rhn', 'rhn'), ('ejare', 'ejare'), ('proje', 'proje')], default='frosh', max_length=5),
        ),
    ]
