# Generated by Django 3.0.5 on 2021-01-06 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('type', models.CharField(choices=[('frosh', 'frosh'), ('villa', 'villa'), ('rhn', 'rhn'), ('ejare', 'ejare'), ('proje', 'proje')], default='frosh', max_length=5)),
                ('file_number', models.TextField(default='1')),
                ('image', models.ImageField(blank=True, default='pic/image_404.png', upload_to='products/%Y/%m/%d')),
                ('image2', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('image3', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('image4', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('image5', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('image6', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('image7', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('image8', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('image9', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('image10', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('image11', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('image12', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('image13', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('image14', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('image15', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('image16', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('image17', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('image18', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('image19', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('image20', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('price_met', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveIntegerField(default=0)),
                ('pol_mhn', models.PositiveIntegerField(default=0)),
                ('pish', models.PositiveIntegerField(default=0)),
                ('bedroom', models.PositiveIntegerField(default=0)),
                ('area', models.PositiveIntegerField(default=0)),
                ('year', models.PositiveIntegerField(default=1)),
                ('parking', models.BooleanField(default=False)),
                ('nastaghi', models.BooleanField(default=False)),
                ('map', models.TextField(blank=True, default='')),
                ('address', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.Category')),
                ('seller', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Seller')),
            ],
            options={
                'ordering': ('-created',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
